title: ParchmentMC
email: website@parchmentmc.org
description: >- # this means to ignore newlines until "baseurl:"
  Open community-sourced parameter names and javadocs
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
twitter_username: mc_parchment
github_username:  ParchmentMC
author:
  name: ParchmentMC

# Build settings
theme: jekyll-yamt

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
twitter:
  username: ParchmentMC
  card: summary
logo: /assets/img/logo.png
social:
  links: #List your social links here
    - https://twitter.com/ParchmentMC
    - https://www.github.com/ParchmentMC
lang: en_US

#Highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never

# Collections
collections:
 - team_members # ParchmentMC team members